### ISSUE TITLE
[Bug report] ML Kit barcode-scanning library v16.2.0 for 16 KB Page Size Compatibility

### ISSUE THREAD

**Issue by jackyk-cognitoiq** [googlesamples/mlkit#976]
**Describe the bug**
When using ML Kit barcode-scanning library v16.2.0 and targeting Android 15 (API level 35), Android studio outputs a warning :

**The native library `arm64-v8a/libbarhopper_v2.so` (from `com.google.mlkit:barcode-scanning:16.2.0`) is not 16 KB aligned**

Starting November 1st, 2025, Google Play will reject new apps or updates that do not comply with the 16 KB page size requirement:

https://developer.android.com/16kb-page-size

I'm aware that the library is compatible with 16 KB page size if I upgrade to v17.3.0. However, due to the issue mentioned in https://github.com/googlesamples/mlkit/issues/367 was not resolved, we are unable to upgrade to that version.

Can you recommend how we should proceed with this? Is it possible to recompile the native library for v16.2.0?

**To Reproduce**
Create an Android project.

Add the ML Kit barcode-scanning dependency in build.gradle - implementation 'com.google.mlkit:barcode-scanning:16.2.0'

Set compileSdk and targetSdk to 35.

Use AGP 8.5+ and Gradle 8.3+.

Observe the warning in the problems window.

**Expected behavior**
The ML Kit barcode-scanning library should have their LOAD segments aligned at 16 KB (0x4000) boundaries, per Play policy.

🚧 Actual Behavior
The affected libbarhopper_v2.so file appear to have default alignment (e.g., 4 KB), which results in compatibility issues with devices using a 16 KB page size.

**SDK Info:**
 com.google.mlkit:barcode-scanning:16.2.0

**Comment by EduardoDevMobile** [comment]
Is there any solution for the com.google.mlkit:barcode-scanning:17.3.0 and the 16kb?

**Comment by luckydut97** [comment]
Has anyone found a workaround for the 16 KB page-size policy when using com.google.android.gms:play-services-mlkit-barcode-scanning:18.3.1? Play Console still flags the bundled libimage_processing_util_jni.so as not supporting 16 KB pages, even on the latest version.

**Comment by KonoGracie** [comment]
The same issue also exists in `com.google.mlkit:barcode-scanning:17.3.0`; the `armeabi-v7a/libbarhopper_v3.so` does not support 16KB page size. I'm using Gradle 8.13 and AGP 8.12.3.

**Comment by dnlrbz** [comment]
using latest Capacitor library there is still a problem with these libs:

- `libbarhopper_v3.so`
- `libimage_processing_util_jni.so`

Google Play requires us to be compatible with 16KB page size, but these libraries still have `.so` extension.

**Comment by maaz-msf** [comment]
iam stuck on using ML KIt library 

 'com.google.mlkit:language-id:17.0.6'

It generates "liblanguage_id_l2c_jni.so" which is 4 KB aligned and there is a deadline.

**Comment by oguibueno** [comment]
> The same issue also exists in `com.google.mlkit:barcode-scanning:17.3.0`; the `armeabi-v7a/libbarhopper_v3.so` does not support 16KB page size. I'm using Gradle 8.13 and AGP 8.12.3.

https://developers.google.com/ml-kit/release-notes#august_7_2024

They fixed here https://issuetracker.google.com/issues/427760954

And here a guy from Google said they won't fix: https://issuetracker.google.com/issues/437112111#comment2 (I assume it's for the 32bit arch)

Locally running a script to check the 16kb thing etc, I got from https://medium.com/easy-flutter/androids-16kb-page-size-explained-flutter-migration-made-simple-c9af18d756c1

script: https://gist.github.com/NitinPraksash9911/76f1793785a232b2aa2bc2e409873955

I've added some an ABI filter that doesn't include the `armeabi-v7a`. If you don't have any filter, it will add all the supported archs by default.

```
ndk {
    abiFilters = ['arm64-v8a', 'x86_64']
}
```

Remove the previous build, build it again and then run the script.

<img width="557" height="166" alt="Image" src="https://github.com/user-attachments/assets/ea071e0b-9fa0-4a38-b77c-c51270d6ea05" />

I haven't tested yet (to submit to google play) but it should work I guess. The problem is if you have to drop support to that 32bit arch, people with the 32bit only, won't be able to install the latest version of your app.


Update:

I've updated flutter to lates (3.35.0) and it worked without any other changes. Meaning that the google play didn't complained about the 16kb anymore.

**Comment by nightism** [comment]
`mlkit-subject-segmentation` still does not support 16 KB. I'm using `com.google.android.gms:play-services-mlkit-subject-segmentation:16.0.0-beta1`

<img width="367" height="219" alt="Image" src="https://github.com/user-attachments/assets/c03e5fca-bdd3-4226-8bfe-635ab997a4c1" />

**Comment by heytsai** [comment]
Regarding `com.google.android.gms:play-services-mlkit-subject-segmentation:16.0.0-beta1`, the same feedback was provided in the https://github.com/googlesamples/mlkit/issues/938#issuecomment-3659008493.

Based on previous investigation, `com.google.android.gms:play-services-mlkit-subject-segmentation:16.0.0-beta1` does not contain `libmlkit-segmentation.so`. This shared object appears to be related to Huawei ML Kit (https://forums.developer.huawei.com/forumPortal/en/topic/0201183498417091123).

**Comment by heytsai** [comment]
I'll close the issue for now.

Feel free to reopen it if you have any further questions or concerns. Thanks!

**Comment by jackyk-cognitoiq** [comment]
@heytsai You comment didn't address the original issue for this bug report.

**Comment by Kelidk** [comment]
Any progress on this? deadline is approaching fast

**Comment by arunkumar459** [comment]
no updates  from anybody .Some body is saying i am able to fix but the steps they are providing actually not fixing the issue

**Comment by Kelidk** [comment]
Any progress on this? deadline is approaching super fast

**Comment by maaz-msf** [comment]
simply updating dependencies resolved my issues !!!
try updating gradle dependencies


Make sure gradle itself is latest

**Comment by Kashif-Rehman** [comment]
Any solution for this?

**Comment by backids99** [comment]
> The same issue also exists in `com.google.mlkit:barcode-scanning:17.3.0`; the `armeabi-v7a/libbarhopper_v3.so` does not support 16KB page size. I'm using Gradle 8.13 and AGP 8.12.3.

any update for this issue? because, i have same issue using **17.3.0 on armeabi-v7a**. Changing **AGP, NDK, and Java Version** still not solved this issue.

**Comment by Goooler** [comment]
This should be closed for now. It has been fixed by newer versions.

`armeabi-v7a` (32-bit) doesn't need 16KB page sizes supports. See https://developer.android.com/guide/practices/page-sizes#alignment-use-script
